### ISSUE TITLE
Türkçe Karakterde Hata

### ISSUE THREAD

**Issue by atagulalan** [utkusen/turkce-wordlist#1]
Wordlist'in bazı kısımlarında aşağıdaki gibi bozulmalar mevcut.
Not: UTF-8 formatı ile açıldı. Windows 1254 ve ISO 8859-9 ile de denedim, ancak sorun çözülmedi.

![eylul](https://user-images.githubusercontent.com/8681330/102723311-fba2ee80-4317-11eb-8a76-92f421be623b.png)

Bazı bulduğum karakterler:

Görülen karakterler | Olması gereken | Kaç kere geçiyor
---|---|---
ãâãâ¼|ü|595
ãâ¯ãâ¿ãâ½|ü, ö|1445
ãâ¼ | ü | 3561
ã¯â¿â½ | ü, ı | 9005
ãâ¾ | ş | 485
ãâ§ | ç | 1901
ãâ¶ | ö | 1860
ãâãâ° | ğ | 49
ãâ | ğ | 887
ãâ° | ğ | 195
ãâ± | ı | 5804
?â?â± | ı | 363
ãâ½ | ı | 902
ãâãâãâãâ± | ı | 47
ãâãâãâãâ | ş | 35
ãâãâãâãâ | ş | 1
ãâãâ | ş | 670
ãâãâ¶ | ö | 331

Küçük not: GitHub Issue'sunda karakterler olması gerektiği gibi gözükmeyebilir. Tabloyu ne olur ne olmaz text halinde şuraya bırakıyorum:
[tablo.txt](https://github.com/utkusen/turkce-wordlist/files/5721463/tablo.txt)

Bu hata giderilmezse aynı şifreler birden fazla gözükebiliyor. Aşağıda öncesi ve sonrasını görebilirsiniz.

Öncesi:
![eskihali](https://user-images.githubusercontent.com/8681330/102723680-a5837a80-431a-11eb-82c2-22c9f6676c36.png)

Sonrası:
![gercekhali](https://user-images.githubusercontent.com/8681330/102723681-a6b4a780-431a-11eb-9d4b-79a1d69bb778.png)

Teşekkürler.

**Comment by utkusen** [comment]
Çok teşekkürler bu detaylı bildirim için. Bunu birkaç kişi daha göndermişti. Bugün çözeceğim.

**Comment by utkusen** [comment]
Halledildi. Tekrar çok teşekkürler
