### ISSUE TITLE
Kişisel Verilerin Açığa Çıkarılması

### ISSUE THREAD

**Issue by atagulalan** [utkusen/turkce-wordlist#2]
https://github.com/utkusen/turkce-wordlist/issues/1 Issue'sundaki görsellerden de anlaşılacağı üzere bazı özel telefon numaraları ve e-posta adresleri şifreler ile birlikte açığa çıkarılmış.

Kişisel verilerin bu wordlist'ten kaldırılması, wordlist'in doğruluğunu arttıracaktır.

Öneri:
- `@gmail`, `@hotmail`, `@outlook` içeren veya mail kurallı ifadesine uyan veriler temizlenebilir
- Telefon numaraları temizlenebilir
- @ ile başlayan ve sonrasında alfanumerik devam eden kullanıcı adları temizlenebilir

**Comment by utkusen** [comment]
Çok teşekkürler bildirim için. Telefon numaraları parolalarda sıkça tercih edildiği için kaldırma taraftarı değilim ama e-posta adreslerini temizleyeceğim.

**Comment by utkusen** [comment]
Halledildi. Tekrar çok teşekkürler

**Comment by moliberga** [comment]
Kardeş senin git geçmişinden haberin yok galiba geçmişi de silmelisin @utkusen
